import { createHash } from "node:crypto";
import { lstatSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { toolCatalog, mcpConfig, codexServers } from "./tool-catalog.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const endpoint = "https://mcp.better-auth.com/mcp";
const digest = (value) => createHash("sha256").update(value).digest("hex");

// Validate every path component before a read or write. Never follow an output
// symlink/junction or overwrite a hard-linked file outside this checkout.
export function safePath(base, relative) {
  if (isAbsolute(relative) || relative.includes("\\") || relative.split("/").some((s) => !s || s === "." || s === "..")) {
    throw new Error(`Unsafe harness path: ${relative}`);
  }
  let path = base;
  const parts = relative.split("/");
  for (const [index, part] of parts.entries()) {
    path = join(path, part);
    let stat;
    try { stat = lstatSync(path); } catch (error) { if (error.code === "ENOENT") continue; throw error; }
    if (stat.isSymbolicLink() || (!stat.isDirectory() && (!stat.isFile() || stat.nlink > 1))) {
      throw new Error(`Refusing linked or special harness path: ${relative}`);
    }
    if (index < parts.length - 1 && !stat.isDirectory()) throw new Error(`Not a directory: ${path}`);
  }
  return path;
}

function read(base, path) { return readFileSync(safePath(base, path), "utf8").replaceAll("\r\n", "\n"); }
function entries(base, path) { return readdirSync(safePath(base, path), { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)); }

// Canonical frontmatter deliberately uses one JSON-quoted scalar per line (valid
// YAML). This avoids a YAML dependency and fails closed on unsupported syntax.
export function parseBrief(source, label) {
  const match = source.match(/^---\n([\s\S]+?)\n---\n([\s\S]+)$/);
  if (!match) throw new Error(`${label}: missing frontmatter or body`);
  const fields = {};
  for (const line of match[1].split("\n")) {
    const field = line.match(/^([a-z]+): (".*")$/);
    if (!field || field[1] in fields) throw new Error(`${label}: use unique JSON-quoted frontmatter scalars`);
    fields[field[1]] = JSON.parse(field[2]);
  }
  if (!/^[a-z][a-z0-9-]{2,49}$/.test(fields.name) || !fields.description?.trim()) throw new Error(`${label}: invalid name/description`);
  return { ...fields, body: match[2].trim() + "\n" };
}

function checkReferences(base, text) {
  for (const [, path] of text.matchAll(/`((?:\.agents\/|go-b2b-starter\/|next_b2b_starter\/|docs\/)[^`\s]+)`/g)) {
    if (path.startsWith(".agents/cache/")) continue; // Explicit optional downloads.
    lstatSync(safePath(base, path.replace(/\/$/, "")));
  }
}

export function sources(base) {
  const data = JSON.parse(read(base, ".agents/sources.json"));
  if (data.schemaVersion !== 1 || data.mcp?.url !== endpoint || data.mcp.server !== "better-auth" ||
      JSON.stringify(data.mcp.allowedTools) !== JSON.stringify(["get_doc", "search_docs"])) throw new Error("Unexpected documentation MCP contract");
  const seen = new Set();
  for (const skill of data.upstreamSkills) {
    if (!/^[a-f0-9]{40}$/.test(skill.revision) || !/^[a-f0-9]{64}$/.test(skill.sha256) ||
        !["best-practices", "organization"].includes(skill.name) || seen.has(skill.name) ||
        skill.repository !== "https://github.com/better-auth/skills" ||
        skill.sourcePath !== `better-auth/${skill.name}/SKILL.md` ||
        skill.cachePath !== `.agents/cache/better-auth/${skill.name}/SKILL.md` ||
        skill.url !== `https://raw.githubusercontent.com/better-auth/skills/${skill.revision}/${skill.sourcePath}` ||
        skill.redistributed !== false) throw new Error("Invalid pinned upstream skill");
    seen.add(skill.name);
    safePath(base, skill.cachePath);
  }
  if (seen.size !== 2) throw new Error("Both pinned Better Auth skills are required");
  return data;
}

export function adapterPlan(base) {
  const manifest = sources(base);
  const catalog = toolCatalog(base);
  if (catalog.servers["better-auth"]?.url !== endpoint ||
      JSON.stringify(catalog.servers["better-auth"].tools) !== JSON.stringify(manifest.mcp.allowedTools)) throw new Error("Unexpected Better Auth documentation contract");
  const mcp = JSON.stringify(mcpConfig(catalog), null, 2) + "\n";
  const generated = "# Generated by node scripts/harness.mjs sync. Edit canonical sources instead.\n";
  const outputs = new Map([
    ["CLAUDE.md", "<!-- Generated by node scripts/harness.mjs sync. -->\n@AGENTS.md\n"],
    ["go-b2b-starter/.claude/CLAUDE.md", "<!-- Generated by node scripts/harness.mjs sync. -->\n@../../AGENTS.md\n\nRead `.agents/skills/go-backend/SKILL.md` from the repository root.\n"],
    ["next_b2b_starter/.claude/CLAUDE.md", "@../../AGENTS.md\n\nRead `next_b2b_starter/README.md` from the repository root for frontend contracts.\n"],
    [".mcp.json", mcp],
    [".cursor/mcp.json", mcp],
    [".codex/config.toml", `${generated}\n${codexServers(catalog)}\n`],
  ]);
  for (const item of entries(base, ".agents/agents")) {
    if (!item.isFile() || !item.name.endsWith(".md")) throw new Error(`Unexpected role entry: ${item.name}`);
    const path = `.agents/agents/${item.name}`;
    const source = read(base, path);
    checkReferences(base, source);
    const role = parseBrief(source, path);
    if (item.name !== `${role.name}.md` || !["write", "read-only"].includes(role.mode)) throw new Error(`Invalid role: ${path}`);
    const readonly = role.mode === "read-only";
    const docsOnly = readonly || role.name === "backend-builder";
    const selected = catalog.enabled.filter((id) => catalog.servers[id].kind === "documentation" || (!docsOnly && catalog.servers[id].kind === "development"));
    const tools = ["Read", "Grep", "Glob", "WebFetch", ...(!readonly ? ["Edit", "Write", "Bash"] : []),
      ...selected.flatMap((id) => (catalog.servers[id].tools || ["*"]).map((name) => `mcp__${id}__${name}`))];
    outputs.set(`.claude/agents/${role.name}.md`, `---\nname: ${JSON.stringify(role.name)}\ndescription: ${JSON.stringify(role.description)}\nmodel: inherit\ncolor: ${role.color}\ntools: ${tools.join(", ")}\n---\n\n<!-- Generated from ${path}; do not edit. -->\n${role.body}`);
    // Provider administration stays in the main authorized session. A filesystem
    // read-only sandbox alone does not prevent remote MCP mutations.
    const roleCatalog = { ...catalog, enabled: catalog.enabled };
    const mcpOverrides = codexServers(roleCatalog, docsOnly).split("\n\n");
    if (!docsOnly) for (const [index, id] of catalog.enabled.entries()) {
      if (catalog.servers[id].kind === "provider") mcpOverrides[index] = `[mcp_servers.workspace-${id}]\nenabled = false`;
    }
    outputs.set(`.codex/agents/${role.name}.toml`, `${generated}name = ${JSON.stringify(role.name)}\ndescription = ${JSON.stringify(role.description)}\n${readonly ? 'sandbox_mode = "read-only"\n' : ""}developer_instructions = ${JSON.stringify(role.body)}\n\n${mcpOverrides.join("\n\n")}\n`);
  }
  const skills = [];
  for (const item of entries(base, ".agents/skills")) {
    if (!item.isDirectory()) throw new Error(`Unexpected skill entry: ${item.name}`);
    const path = `.agents/skills/${item.name}/SKILL.md`;
    const source = read(base, path);
    checkReferences(base, source);
    if (parseBrief(source, path).name !== item.name) throw new Error(`Skill name mismatch: ${path}`);
    skills.push(item.name);
    outputs.set(`.claude/skills/${item.name}/SKILL.md`, source.replace(/\n---\n/, `\n---\n\n<!-- Generated from ${path}; do not edit. -->\n`));
  }
  if (JSON.stringify(skills.sort()) !== JSON.stringify([...manifest.authoredHere].sort())) throw new Error("Skill provenance inventory is incomplete");
  // Preflight ALL destinations before changing ANY files.
  for (const path of outputs.keys()) safePath(base, path);
  for (const directory of [".codex/agents", ".claude/agents", ".claude/skills"]) {
    let existing;
    try { existing = entries(base, directory); } catch (error) { if (error.code === "ENOENT") continue; throw error; }
    for (const item of existing) {
      const path = `${directory}/${item.name}`;
      const expected = directory.endsWith("skills") ? `${path}/SKILL.md` : path;
      if (!outputs.has(expected)) throw new Error(`Unmanaged adapter: ${path}. Move its source into .agents first.`);
      if (directory.endsWith("skills")) for (const file of entries(base, path)) {
        if (file.name !== "SKILL.md") throw new Error(`Unmanaged skill adapter: ${path}/${file.name}`);
      }
    }
  }
  return outputs;
}

export function sync(base, check = false) {
  const plan = adapterPlan(base);
  const drift = [];
  for (const [path, content] of plan) {
    let actual;
    try { actual = read(base, path); } catch (error) { if (error.code !== "ENOENT") throw error; }
    if (actual !== content) drift.push(path);
  }
  if (check && drift.length) throw new Error(`Generated adapter drift: ${drift.join(", ")}. Run node scripts/harness.mjs sync.`);
  if (!check) for (const path of drift) {
    const destination = safePath(base, path);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, plan.get(path));
  }
  for (const skill of sources(base).upstreamSkills) {
    let cached;
    try { cached = readFileSync(safePath(base, skill.cachePath)); } catch (error) { if (error.code === "ENOENT") continue; throw error; }
    if (digest(cached) !== skill.sha256) throw new Error(`Modified upstream cache: ${skill.cachePath}`);
  }
  return plan.size;
}

export async function fetchSkills(base, fetcher = fetch) {
  const { upstreamSkills } = sources(base);
  // Download and verify both files before replacing any cache content.
  const contents = await Promise.all(upstreamSkills.map(async (skill) => {
    const response = await fetcher(skill.url, { redirect: "error", signal: AbortSignal.timeout(20000) });
    if (!response.ok) throw new Error(`Skill download failed (${response.status})`);
    const bytes = Buffer.from(await response.arrayBuffer());
    if (bytes.length > 1024 * 1024 || digest(bytes) !== skill.sha256) throw new Error(`Upstream skill digest mismatch: ${skill.name}`);
    return bytes;
  }));
  upstreamSkills.forEach((skill, index) => {
    const destination = safePath(base, skill.cachePath);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, contents[index]);
  });
}

export async function checkMcp(base, fetcher = fetch) {
  const { mcp } = sources(base);
  let session;
  let id = 0;
  async function rpc(method, params) {
    const notification = method.startsWith("notifications/");
    const requestId = ++id;
    const response = await fetcher(mcp.url, { method: "POST", redirect: "error", signal: AbortSignal.timeout(20000),
      headers: { "Content-Type": "application/json", Accept: "application/json, text/event-stream", "MCP-Protocol-Version": "2025-03-26", ...(session ? { "Mcp-Session-Id": session } : {}) },
      body: JSON.stringify({ jsonrpc: "2.0", ...(!notification ? { id: requestId } : {}), method, params }) });
    if (!response.ok) throw new Error(`Documentation MCP failed (${response.status})`);
    session = response.headers.get("mcp-session-id") || session;
    if (notification) return {};
    const raw = await response.text();
    const payloads = response.headers.get("content-type")?.includes("text/event-stream")
      ? raw.split(/\r?\n/).filter((line) => line.startsWith("data: ")).map((line) => JSON.parse(line.slice(6))) : [JSON.parse(raw)];
    const result = payloads.find((payload) => payload.id === requestId);
    if (!result?.result || result.error) throw new Error(`Invalid documentation MCP result for ${method}`);
    return result.result;
  }
  await rpc("initialize", { protocolVersion: "2025-03-26", capabilities: {}, clientInfo: { name: "starter-harness-check", version: "1.0.0" } });
  await rpc("notifications/initialized", {});
  const result = await rpc("tools/list", {});
  const listed = result.tools?.map((tool) => tool.name).sort();
  if (JSON.stringify(listed) !== JSON.stringify(mcp.allowedTools) || result.tools.some((tool) => tool.annotations?.readOnlyHint !== true || tool.annotations?.destructiveHint !== false)) {
    throw new Error("Documentation MCP tools changed; review before use");
  }
  const document = await rpc("tools/call", { name: "get_doc", arguments: { path: "/llms.txt" } });
  if (document.isError || !document.content?.some((item) => item.type === "text" && item.text.includes("https://better-auth.com/"))) throw new Error("Documentation MCP did not return the version index");
  return listed;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const command = process.argv[2];
    if (process.argv.length !== 3) throw new Error("Usage: node scripts/harness.mjs sync|check|tools|fetch-skills|check-mcp");
    if (command === "sync" || command === "check") console.log(`${command}: ${sync(root, command === "check")} generated adapters verified`);
    else if (command === "fetch-skills") { await fetchSkills(root); console.log("Fetched two hash-verified official skills into the ignored local cache."); }
    else if (command === "check-mcp") console.log(`Read-only documentation MCP verified: ${(await checkMcp(root)).join(", ")}`);
    else if (command === "tools") {
      const catalog = toolCatalog(root);
      for (const [id, server] of Object.entries(catalog.servers)) console.log(`${catalog.enabled.includes(id) ? "enabled" : "optional"}\t${id}\t${server.version || server.auth}\t${server.purpose}`);
    }
    else throw new Error(`Unknown harness command: ${command}`);
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
